name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        erlang_version: ["27", "28"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang_version }}
          gleam-version: "1.11.1"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
